// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authservice.proto

package authService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignUpData struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpData) Reset()         { *m = SignUpData{} }
func (m *SignUpData) String() string { return proto.CompactTextString(m) }
func (*SignUpData) ProtoMessage()    {}
func (*SignUpData) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{0}
}
func (m *SignUpData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpData.Unmarshal(m, b)
}
func (m *SignUpData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpData.Marshal(b, m, deterministic)
}
func (dst *SignUpData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpData.Merge(dst, src)
}
func (m *SignUpData) XXX_Size() int {
	return xxx_messageInfo_SignUpData.Size(m)
}
func (m *SignUpData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpData.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpData proto.InternalMessageInfo

func (m *SignUpData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignUpData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInData struct {
	Login                string   `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInData) Reset()         { *m = SignInData{} }
func (m *SignInData) String() string { return proto.CompactTextString(m) }
func (*SignInData) ProtoMessage()    {}
func (*SignInData) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{1}
}
func (m *SignInData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInData.Unmarshal(m, b)
}
func (m *SignInData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInData.Marshal(b, m, deterministic)
}
func (dst *SignInData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInData.Merge(dst, src)
}
func (m *SignInData) XXX_Size() int {
	return xxx_messageInfo_SignInData.Size(m)
}
func (m *SignInData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInData.DiscardUnknown(m)
}

var xxx_messageInfo_SignInData proto.InternalMessageInfo

func (m *SignInData) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *SignInData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateUserData struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserData) Reset()         { *m = UpdateUserData{} }
func (m *UpdateUserData) String() string { return proto.CompactTextString(m) }
func (*UpdateUserData) ProtoMessage()    {}
func (*UpdateUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{2}
}
func (m *UpdateUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserData.Unmarshal(m, b)
}
func (m *UpdateUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserData.Marshal(b, m, deterministic)
}
func (dst *UpdateUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserData.Merge(dst, src)
}
func (m *UpdateUserData) XXX_Size() int {
	return xxx_messageInfo_UpdateUserData.Size(m)
}
func (m *UpdateUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserData.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserData proto.InternalMessageInfo

func (m *UpdateUserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UpdatePasswordData struct {
	NewPassword          string   `protobuf:"bytes,1,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	PasswordConfirm      string   `protobuf:"bytes,2,opt,name=PasswordConfirm,proto3" json:"PasswordConfirm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordData) Reset()         { *m = UpdatePasswordData{} }
func (m *UpdatePasswordData) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordData) ProtoMessage()    {}
func (*UpdatePasswordData) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{3}
}
func (m *UpdatePasswordData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordData.Unmarshal(m, b)
}
func (m *UpdatePasswordData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordData.Marshal(b, m, deterministic)
}
func (dst *UpdatePasswordData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordData.Merge(dst, src)
}
func (m *UpdatePasswordData) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordData.Size(m)
}
func (m *UpdatePasswordData) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordData.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordData proto.InternalMessageInfo

func (m *UpdatePasswordData) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *UpdatePasswordData) GetPasswordConfirm() string {
	if m != nil {
		return m.PasswordConfirm
	}
	return ""
}

type RemoveUserData struct {
	Password             string   `protobuf:"bytes,1,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveUserData) Reset()         { *m = RemoveUserData{} }
func (m *RemoveUserData) String() string { return proto.CompactTextString(m) }
func (*RemoveUserData) ProtoMessage()    {}
func (*RemoveUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{4}
}
func (m *RemoveUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveUserData.Unmarshal(m, b)
}
func (m *RemoveUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveUserData.Marshal(b, m, deterministic)
}
func (dst *RemoveUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveUserData.Merge(dst, src)
}
func (m *RemoveUserData) XXX_Size() int {
	return xxx_messageInfo_RemoveUserData.Size(m)
}
func (m *RemoveUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveUserData.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveUserData proto.InternalMessageInfo

func (m *RemoveUserData) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignUpRequest struct {
	Data                 *SignUpData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{5}
}
func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (dst *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(dst, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetData() *SignUpData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SignInRequest struct {
	Data                 *SignInData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{6}
}
func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (dst *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(dst, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetData() *SignInData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateAuthRequest struct {
	Id                   int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserData             *UpdateUserData `protobuf:"bytes,2,opt,name=userData,proto3" json:"userData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpdateAuthRequest) Reset()         { *m = UpdateAuthRequest{} }
func (m *UpdateAuthRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAuthRequest) ProtoMessage()    {}
func (*UpdateAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{7}
}
func (m *UpdateAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAuthRequest.Unmarshal(m, b)
}
func (m *UpdateAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAuthRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAuthRequest.Merge(dst, src)
}
func (m *UpdateAuthRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAuthRequest.Size(m)
}
func (m *UpdateAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAuthRequest proto.InternalMessageInfo

func (m *UpdateAuthRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateAuthRequest) GetUserData() *UpdateUserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

type UpdatePasswordRequest struct {
	Id                   int64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PasswordData         *UpdatePasswordData `protobuf:"bytes,2,opt,name=passwordData,proto3" json:"passwordData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{8}
}
func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(dst, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePasswordRequest) GetPasswordData() *UpdatePasswordData {
	if m != nil {
		return m.PasswordData
	}
	return nil
}

type RemoveAuthRequest struct {
	Id                   int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RemoveData           *RemoveUserData `protobuf:"bytes,2,opt,name=removeData,proto3" json:"removeData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RemoveAuthRequest) Reset()         { *m = RemoveAuthRequest{} }
func (m *RemoveAuthRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveAuthRequest) ProtoMessage()    {}
func (*RemoveAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{9}
}
func (m *RemoveAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAuthRequest.Unmarshal(m, b)
}
func (m *RemoveAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAuthRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAuthRequest.Merge(dst, src)
}
func (m *RemoveAuthRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveAuthRequest.Size(m)
}
func (m *RemoveAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAuthRequest proto.InternalMessageInfo

func (m *RemoveAuthRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RemoveAuthRequest) GetRemoveData() *RemoveUserData {
	if m != nil {
		return m.RemoveData
	}
	return nil
}

type SignUpResponse struct {
	JwtToken             string   `protobuf:"bytes,1,opt,name=jwtToken,proto3" json:"jwtToken,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Fields               []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{10}
}
func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (dst *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(dst, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetJwtToken() string {
	if m != nil {
		return m.JwtToken
	}
	return ""
}

func (m *SignUpResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SignUpResponse) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type SignInResponse struct {
	JwtToken             string   `protobuf:"bytes,1,opt,name=jwtToken,proto3" json:"jwtToken,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Fields               []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{11}
}
func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (dst *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(dst, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetJwtToken() string {
	if m != nil {
		return m.JwtToken
	}
	return ""
}

func (m *SignInResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SignInResponse) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type UpdateAuthResponse struct {
	JwtToken             string   `protobuf:"bytes,1,opt,name=jwtToken,proto3" json:"jwtToken,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Fields               []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAuthResponse) Reset()         { *m = UpdateAuthResponse{} }
func (m *UpdateAuthResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAuthResponse) ProtoMessage()    {}
func (*UpdateAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{12}
}
func (m *UpdateAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAuthResponse.Unmarshal(m, b)
}
func (m *UpdateAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAuthResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAuthResponse.Merge(dst, src)
}
func (m *UpdateAuthResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAuthResponse.Size(m)
}
func (m *UpdateAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAuthResponse proto.InternalMessageInfo

func (m *UpdateAuthResponse) GetJwtToken() string {
	if m != nil {
		return m.JwtToken
	}
	return ""
}

func (m *UpdateAuthResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateAuthResponse) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type UpdatePasswordResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Fields               []string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordResponse) Reset()         { *m = UpdatePasswordResponse{} }
func (m *UpdatePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordResponse) ProtoMessage()    {}
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{13}
}
func (m *UpdatePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordResponse.Unmarshal(m, b)
}
func (m *UpdatePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordResponse.Marshal(b, m, deterministic)
}
func (dst *UpdatePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordResponse.Merge(dst, src)
}
func (m *UpdatePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordResponse.Size(m)
}
func (m *UpdatePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordResponse proto.InternalMessageInfo

func (m *UpdatePasswordResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdatePasswordResponse) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type RemoveAuthResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Fields               []string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveAuthResponse) Reset()         { *m = RemoveAuthResponse{} }
func (m *RemoveAuthResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveAuthResponse) ProtoMessage()    {}
func (*RemoveAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authService_efe452945289a571, []int{14}
}
func (m *RemoveAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAuthResponse.Unmarshal(m, b)
}
func (m *RemoveAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAuthResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAuthResponse.Merge(dst, src)
}
func (m *RemoveAuthResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveAuthResponse.Size(m)
}
func (m *RemoveAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAuthResponse proto.InternalMessageInfo

func (m *RemoveAuthResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RemoveAuthResponse) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func init() {
	proto.RegisterType((*SignUpData)(nil), "SignUpData")
	proto.RegisterType((*SignInData)(nil), "SignInData")
	proto.RegisterType((*UpdateUserData)(nil), "UpdateUserData")
	proto.RegisterType((*UpdatePasswordData)(nil), "UpdatePasswordData")
	proto.RegisterType((*RemoveUserData)(nil), "RemoveUserData")
	proto.RegisterType((*SignUpRequest)(nil), "SignUpRequest")
	proto.RegisterType((*SignInRequest)(nil), "SignInRequest")
	proto.RegisterType((*UpdateAuthRequest)(nil), "UpdateAuthRequest")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "UpdatePasswordRequest")
	proto.RegisterType((*RemoveAuthRequest)(nil), "RemoveAuthRequest")
	proto.RegisterType((*SignUpResponse)(nil), "SignUpResponse")
	proto.RegisterType((*SignInResponse)(nil), "SignInResponse")
	proto.RegisterType((*UpdateAuthResponse)(nil), "UpdateAuthResponse")
	proto.RegisterType((*UpdatePasswordResponse)(nil), "UpdatePasswordResponse")
	proto.RegisterType((*RemoveAuthResponse)(nil), "RemoveAuthResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	UpdateAuth(ctx context.Context, in *UpdateAuthRequest, opts ...grpc.CallOption) (*UpdateAuthResponse, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*UpdatePasswordResponse, error)
	RemoveAuth(ctx context.Context, in *RemoveAuthRequest, opts ...grpc.CallOption) (*RemoveAuthResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, "/AuthService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/AuthService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateAuth(ctx context.Context, in *UpdateAuthRequest, opts ...grpc.CallOption) (*UpdateAuthResponse, error) {
	out := new(UpdateAuthResponse)
	err := c.cc.Invoke(ctx, "/AuthService/UpdateAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*UpdatePasswordResponse, error) {
	out := new(UpdatePasswordResponse)
	err := c.cc.Invoke(ctx, "/AuthService/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RemoveAuth(ctx context.Context, in *RemoveAuthRequest, opts ...grpc.CallOption) (*RemoveAuthResponse, error) {
	out := new(RemoveAuthResponse)
	err := c.cc.Invoke(ctx, "/AuthService/RemoveAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	UpdateAuth(context.Context, *UpdateAuthRequest) (*UpdateAuthResponse, error)
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*UpdatePasswordResponse, error)
	RemoveAuth(context.Context, *RemoveAuthRequest) (*RemoveAuthResponse, error)
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/UpdateAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateAuth(ctx, req.(*UpdateAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RemoveAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RemoveAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/RemoveAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RemoveAuth(ctx, req.(*RemoveAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _AuthService_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _AuthService_SignIn_Handler,
		},
		{
			MethodName: "UpdateAuth",
			Handler:    _AuthService_UpdateAuth_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _AuthService_UpdatePassword_Handler,
		},
		{
			MethodName: "RemoveAuth",
			Handler:    _AuthService_RemoveAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authservice.proto",
}

func init() { proto.RegisterFile("authservice.proto", fileDescriptor_authService_efe452945289a571) }

var fileDescriptor_authService_efe452945289a571 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0x53, 0xa8, 0xc6, 0x0d, 0xa4, 0xaa, 0x07, 0xa5, 0xca, 0x0b, 0x53, 0x9e, 0x86, 0x40,
	0x06, 0x15, 0x21, 0xde, 0x90, 0x3a, 0x3e, 0xa4, 0x4a, 0x08, 0x4d, 0xde, 0xfa, 0xc2, 0x03, 0xc2,
	0x50, 0x6f, 0x04, 0x16, 0x3b, 0x38, 0xe9, 0xfa, 0x47, 0xf8, 0xc1, 0x73, 0xfc, 0x91, 0xc4, 0x49,
	0xb7, 0x87, 0x69, 0x6f, 0xbe, 0xf6, 0xb9, 0xe7, 0x5e, 0x9f, 0x73, 0x6d, 0x98, 0xd0, 0x4d, 0xf9,
	0xfb, 0x84, 0xc9, 0xcb, 0xf4, 0x17, 0xc3, 0xb9, 0x14, 0xa5, 0x48, 0xbe, 0x01, 0x9c, 0xa4, 0xe7,
	0x7c, 0x95, 0x7f, 0xa4, 0x25, 0x45, 0x8f, 0xe1, 0xfe, 0xa7, 0x8c, 0xa6, 0x17, 0xb3, 0xc1, 0xc1,
	0xe0, 0xf0, 0x01, 0x31, 0x01, 0x8a, 0x61, 0x6f, 0x55, 0x30, 0xc9, 0x69, 0xc6, 0x66, 0x81, 0x3e,
	0xa8, 0xe3, 0xea, 0xec, 0x98, 0x16, 0xc5, 0x56, 0xc8, 0xf5, 0x6c, 0x68, 0xce, 0x5c, 0x9c, 0xbc,
	0x37, 0xdc, 0x4b, 0xee, 0xb8, 0xbf, 0x88, 0xf3, 0x94, 0x3b, 0x6e, 0x1d, 0x78, 0xf9, 0x41, 0x27,
	0xff, 0x08, 0xa2, 0x55, 0xbe, 0xa6, 0x25, 0xab, 0xaa, 0xdd, 0xae, 0xbf, 0xe4, 0x07, 0x20, 0xc3,
	0xe1, 0x58, 0x35, 0xcf, 0x01, 0x84, 0x5f, 0xd9, 0xb6, 0x2e, 0x6c, 0xd8, 0xda, 0x5b, 0xe8, 0x10,
	0xc6, 0x6e, 0xfd, 0x41, 0xf0, 0xb3, 0x54, 0x66, 0x96, 0xba, 0xbb, 0x9d, 0xbc, 0x84, 0x88, 0xb0,
	0x4c, 0x5c, 0x36, 0x5d, 0xb6, 0xef, 0x34, 0xe8, 0xdc, 0xe9, 0x35, 0x3c, 0x32, 0x7a, 0x13, 0xf6,
	0x6f, 0xc3, 0x8a, 0x12, 0x3d, 0x83, 0x7b, 0xaa, 0x3d, 0xaa, 0x81, 0xe1, 0x3c, 0xc4, 0x8d, 0x1b,
	0x44, 0x1f, 0xb8, 0x8c, 0x25, 0xbf, 0x29, 0xc3, 0x68, 0x6c, 0x33, 0x8e, 0x61, 0x62, 0xee, 0xbc,
	0x50, 0x76, 0xbb, 0xac, 0x08, 0x82, 0xd4, 0xb4, 0x33, 0x24, 0x6a, 0x85, 0x5e, 0xc0, 0xde, 0xc6,
	0x36, 0xac, 0x6f, 0x16, 0xce, 0xc7, 0xd8, 0x57, 0x9b, 0xd4, 0x00, 0xa5, 0xe2, 0x13, 0x5f, 0xc5,
	0xeb, 0x58, 0xdf, 0xc1, 0xc3, 0xbc, 0x25, 0xb4, 0x65, 0xde, 0xc7, 0x7d, 0x0f, 0x88, 0x07, 0x4c,
	0x4e, 0x61, 0x62, 0x54, 0xbc, 0xa9, 0xe7, 0x57, 0x00, 0x52, 0x83, 0xbc, 0xae, 0x7d, 0xf5, 0x49,
	0x0b, 0xa2, 0xa6, 0x3b, 0x72, 0x6a, 0x17, 0xb9, 0xe0, 0x85, 0x9e, 0xd7, 0x3f, 0xdb, 0xf2, 0x54,
	0xfc, 0x65, 0x6e, 0x10, 0xeb, 0xb8, 0x9a, 0x2e, 0x26, 0xa5, 0x90, 0xd6, 0x69, 0x13, 0xa0, 0x29,
	0x8c, 0xce, 0x52, 0x76, 0xb1, 0x2e, 0xd4, 0x7c, 0x0f, 0xd5, 0xb6, 0x8d, 0x1c, 0x77, 0xe5, 0xcb,
	0x9d, 0x73, 0x7f, 0x77, 0x53, 0x6b, 0xd4, 0xb8, 0x73, 0xfe, 0xcf, 0x30, 0xed, 0xfa, 0x69, 0x6b,
	0xd4, 0x3c, 0x83, 0xdd, 0x3c, 0x81, 0xc7, 0x73, 0x04, 0xa8, 0xed, 0xda, 0x6d, 0x38, 0xe6, 0xff,
	0x03, 0x08, 0x17, 0xcd, 0xbf, 0x84, 0x9e, 0xc3, 0xc8, 0x78, 0x86, 0x22, 0xec, 0x3d, 0x95, 0x78,
	0x8c, 0x3b, 0x66, 0x5a, 0xe8, 0x92, 0x5b, 0x68, 0xfd, 0x46, 0x2c, 0xb4, 0xe5, 0xcd, 0x5b, 0x80,
	0x46, 0x51, 0x84, 0x70, 0xef, 0x81, 0xc4, 0xfb, 0x78, 0x87, 0xe4, 0x0b, 0xf7, 0x05, 0xd5, 0x1f,
	0xc3, 0x14, 0xef, 0x7c, 0x09, 0xf1, 0x53, 0x7c, 0x8d, 0xa2, 0xaa, 0x72, 0xa3, 0x91, 0xaa, 0xdc,
	0x1b, 0x73, 0x55, 0xb9, 0x2f, 0xe2, 0xcf, 0x91, 0xfe, 0x9f, 0xdf, 0x5c, 0x05, 0x00, 0x00, 0xff,
	0xff, 0xdc, 0x43, 0x27, 0x4f, 0xb4, 0x05, 0x00, 0x00,
}
