sudo: false

language: go

go:
  - 1.11.x

services: docker

env:
  - GO111MODULE=on USE_DOCKER_DB=on

install: true

before_script:
  - go mod tidy
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - cd build && ./initial.sh && ./db_run_container.sh && cd ..

script:
  - go build cmd/server/main.go
  - go test -v -race ./...
  - golangci-lint run -c .golangci.yml

after_script:
  - cd build && ./clear_up_containers.sh & cd ..