sudo: false

language: go

go:
  - 1.11.x

services: docker

env:
  - GO111MODULE=on COLORS_SERVICE_USE_MODE=USE_DOCKER_DB COLORS_CONFIG_PATH="$GOPATH/src/github.com/go-park-mail-ru/2019_1_OPG_plus_2/"

install: true

before_script:
  - go mod tidy
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - cd build && ./initial.sh && ./db_run_container.sh && cd ..

script:
  - go build cmd/server/main.go
  - go test -v -race ./...
  - golangci-lint run -c .golangci.yml

after_script:
  - cd build && ./clear_up_containers.sh & cd ..