sudo: false

language: go

go:
  - 1.11.x
  - master


env:
  - GO111MODULE=on TEST_DB=on

install: true

before_script:
  - go mod tidy

script:
  - go build cmd/server/main.go
  - go vet ./...
  - go test -v -race ./...