sudo: false

language: go

go:
  - 1.11.x
  - master

before_script:
  - export GO111MODULE=on
  - go mod download

script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled