sudo: false

language: go

go:
  - 1.11.x
  - master


env:
  - GO111MODULE=on

install: true

go_import_path: $GOPATH/src/github.com/go-park-mail-ru/2019_1_OPG_plus_2/

before_script:
  - go mod tidy

script:
  - go build
  - go test -v -race ./...